-- IMPORTAÇÃO INICIAL DOS PRODUTOS DO PDF (59 itens)
-- Gerado por scripts/generate-seed.mjs — não edite à mão.
--
-- Seguro para executar mais de uma vez: a chave única é o "slug" e o comando usa
-- ON CONFLICT DO NOTHING. Itens já existentes NÃO são alterados, então suas edições
-- futuras de nome, preço, disponibilidade, visibilidade e fotos nunca são sobrescritas.
-- (Se você excluir um produto no painel e rodar este arquivo de novo, ele volta.)

insert into public.products (slug, name, price_cents, category)
values
  ('masculino-alpine-homme-sport', 'Alpine Homme Sport', 35000, 'masculino'),
  ('masculino-kingsman', 'Kingsman', 35000, 'masculino'),
  ('masculino-maitre-de-blue', 'Maître de Blue', 35000, 'masculino'),
  ('masculino-moondrift-blue-intense', 'Moondrift Blue Intense', 35000, 'masculino'),
  ('masculino-salvo', 'SALVO', 35000, 'masculino'),
  ('masculino-al-noble-wazeer', 'Al Noble Wazeer', 38000, 'masculino'),
  ('masculino-jean-lowe-fantasme', 'Jean Lowe Fantasme', 38000, 'masculino'),
  ('masculino-jean-lowe-vibe', 'Jean Lowe Vibe', 38000, 'masculino'),
  ('masculino-asad', 'Asad', 45000, 'masculino'),
  ('masculino-fakhar-lattafa-black', 'Fakhar Lattafa Black', 45000, 'masculino'),
  ('masculino-nocturno-elixir', 'Nocturno Elixir', 45000, 'masculino'),
  ('masculino-pacific-aura', 'Pacific Aura', 45000, 'masculino'),
  ('masculino-hawas-kobra', 'Hawas Kobra', 48000, 'masculino'),
  ('masculino-so-candid-pour-homme', 'So Candid Pour Homme', 50000, 'masculino'),
  ('masculino-hawas', 'Hawas', 55000, 'masculino'),
  ('masculino-armaf-cristian-provenzano', 'Armaf Cristian Provenzano', 70000, 'masculino'),
  ('masculino-thriller', 'Thriller', 80000, 'masculino'),
  ('masculino-club-de-nuit-elite', 'Club de Nuit Elite', 85000, 'masculino'),
  ('masculino-regent-royal-maison-asrar', 'Regent Royal Maison Asrar', 85000, 'masculino'),
  ('feminino-olivia-30-ml', 'Olivia 30 ml', 13000, 'feminino'),
  ('feminino-miss-surf-cherie', 'Miss Surf Chérie', 28000, 'feminino'),
  ('feminino-ameerat-al-arab', 'Ameerat Al Arab', 35000, 'feminino'),
  ('feminino-delilah-blanc', 'Delilah Blanc', 35000, 'feminino'),
  ('feminino-glacier-bella', 'Glacier Bella', 35000, 'feminino'),
  ('feminino-so-glam', 'So Glam', 35000, 'feminino'),
  ('feminino-watani', 'Watani', 35000, 'feminino'),
  ('feminino-athena', 'Athena', 45000, 'feminino'),
  ('feminino-fakhar-lattafa-white', 'Fakhar Lattafa White', 45000, 'feminino'),
  ('feminino-haya', 'Haya', 45000, 'feminino'),
  ('feminino-sabah-al-ward', 'Sabah Al Ward', 45000, 'feminino'),
  ('feminino-pink-eclipse', 'Pink Eclipse', 46000, 'feminino'),
  ('feminino-club-de-nuit-maleka', 'Club de Nuit Maleka', 55000, 'feminino'),
  ('feminino-club-de-nuit-woman', 'Club de Nuit Woman', 55000, 'feminino'),
  ('feminino-najma-mawwal', 'Najma Mawwal', 60000, 'feminino'),
  ('unissex-xerjoff-erba-gold', 'Xerjoff Erba Gold', 25000, 'unissex'),
  ('unissex-philos-pura', 'Philos Pura', 30000, 'unissex'),
  ('unissex-attar-al-wesal', 'Attar Al Wesal', 35000, 'unissex'),
  ('unissex-bidaya-maktub-gold', 'Bidaya Maktub Gold', 35000, 'unissex'),
  ('unissex-dynasty', 'Dynasty', 35000, 'unissex'),
  ('unissex-hayaati', 'Hayaati', 35000, 'unissex'),
  ('unissex-menocline-05', 'Menocline 05', 35000, 'unissex'),
  ('unissex-sultan', 'Sultan', 35000, 'unissex'),
  ('unissex-almamlaka', 'Almamlaka', 38000, 'unissex'),
  ('unissex-al-haramain-amber-oud', 'Al Haramain Amber Oud', 45000, 'unissex'),
  ('unissex-alfares', 'Alfares', 45000, 'unissex'),
  ('unissex-ghost-spectre', 'Ghost Spectre', 45000, 'unissex'),
  ('unissex-mishlah', 'Mishlah', 45000, 'unissex'),
  ('unissex-electric-afnan', 'Electric Afnan', 46000, 'unissex'),
  ('unissex-club-de-nuit-iconic', 'Club de Nuit Iconic', 55000, 'unissex'),
  ('unissex-emmer', 'Emmer', 55000, 'unissex'),
  ('unissex-liam', 'Liam', 55000, 'unissex'),
  ('unissex-liquid-brun', 'Liquid Brun', 65000, 'unissex'),
  ('unissex-mussamam-black', 'Mussamam Black', 65000, 'unissex'),
  ('unissex-mussamam-marrom', 'Mussamam Marrom', 65000, 'unissex'),
  ('unissex-mussamam-white', 'Mussamam White', 65000, 'unissex'),
  ('unissex-ravine-ginger', 'Ravine Ginger', 65000, 'unissex'),
  ('cuidados-salvo-body-cream', 'SALVO Body Cream', 23000, 'cuidados'),
  ('cuidados-body-cream-asad', 'Body Cream Asad', 30000, 'cuidados'),
  ('cuidados-retinal-shot', 'Retinal Shot', 35000, 'cuidados')
on conflict (slug) do nothing;
