// Fonte: PDF do catálogo (nomes, valores e categorias exatamente como no PDF).
// Preço em centavos. A ordem segue a do PDF.
export const PRODUCTS = [
  // PERFUMES MASCULINOS
  { category: 'masculino', name: 'Alpine Homme Sport', cents: 35000 },
  { category: 'masculino', name: 'Kingsman', cents: 35000 },
  { category: 'masculino', name: 'Maître de Blue', cents: 35000 },
  { category: 'masculino', name: 'Moondrift Blue Intense', cents: 35000 },
  { category: 'masculino', name: 'SALVO', cents: 35000 },
  { category: 'masculino', name: 'Al Noble Wazeer', cents: 38000 },
  { category: 'masculino', name: 'Jean Lowe Fantasme', cents: 38000 },
  { category: 'masculino', name: 'Jean Lowe Vibe', cents: 38000 },
  { category: 'masculino', name: 'Asad', cents: 45000 },
  { category: 'masculino', name: 'Fakhar Lattafa Black', cents: 45000 },
  { category: 'masculino', name: 'Nocturno Elixir', cents: 45000 },
  { category: 'masculino', name: 'Pacific Aura', cents: 45000 },
  { category: 'masculino', name: 'Hawas Kobra', cents: 48000 },
  { category: 'masculino', name: 'So Candid Pour Homme', cents: 50000 },
  { category: 'masculino', name: 'Hawas', cents: 55000 },
  { category: 'masculino', name: 'Armaf Cristian Provenzano', cents: 70000 },
  { category: 'masculino', name: 'Thriller', cents: 80000 },
  { category: 'masculino', name: 'Club de Nuit Elite', cents: 85000 },
  { category: 'masculino', name: 'Regent Royal Maison Asrar', cents: 85000 },

  // PERFUMES FEMININOS
  { category: 'feminino', name: 'Olivia 30 ml', cents: 13000 },
  { category: 'feminino', name: 'Miss Surf Chérie', cents: 28000 },
  { category: 'feminino', name: 'Ameerat Al Arab', cents: 35000 },
  { category: 'feminino', name: 'Delilah Blanc', cents: 35000 },
  { category: 'feminino', name: 'Glacier Bella', cents: 35000 },
  { category: 'feminino', name: 'So Glam', cents: 35000 },
  { category: 'feminino', name: 'Watani', cents: 35000 },
  { category: 'feminino', name: 'Athena', cents: 45000 },
  { category: 'feminino', name: 'Fakhar Lattafa White', cents: 45000 },
  { category: 'feminino', name: 'Haya', cents: 45000 },
  { category: 'feminino', name: 'Sabah Al Ward', cents: 45000 },
  { category: 'feminino', name: 'Pink Eclipse', cents: 46000 },
  { category: 'feminino', name: 'Club de Nuit Maleka', cents: 55000 },
  { category: 'feminino', name: 'Club de Nuit Woman', cents: 55000 },
  { category: 'feminino', name: 'Najma Mawwal', cents: 60000 },

  // PERFUMES UNISSEX
  { category: 'unissex', name: 'Xerjoff Erba Gold', cents: 25000 },
  { category: 'unissex', name: 'Philos Pura', cents: 30000 },
  { category: 'unissex', name: 'Attar Al Wesal', cents: 35000 },
  { category: 'unissex', name: 'Bidaya Maktub Gold', cents: 35000 },
  { category: 'unissex', name: 'Dynasty', cents: 35000 },
  { category: 'unissex', name: 'Hayaati', cents: 35000 },
  { category: 'unissex', name: 'Menocline 05', cents: 35000 },
  { category: 'unissex', name: 'Sultan', cents: 35000 },
  { category: 'unissex', name: 'Almamlaka', cents: 38000 },
  { category: 'unissex', name: 'Al Haramain Amber Oud', cents: 45000 },
  { category: 'unissex', name: 'Alfares', cents: 45000 },
  { category: 'unissex', name: 'Ghost Spectre', cents: 45000 },
  { category: 'unissex', name: 'Mishlah', cents: 45000 },
  { category: 'unissex', name: 'Electric Afnan', cents: 46000 },
  { category: 'unissex', name: 'Club de Nuit Iconic', cents: 55000 },
  { category: 'unissex', name: 'Emmer', cents: 55000 },
  { category: 'unissex', name: 'Liam', cents: 55000 },
  { category: 'unissex', name: 'Liquid Brun', cents: 65000 },
  { category: 'unissex', name: 'Mussamam Black', cents: 65000 },
  { category: 'unissex', name: 'Mussamam Marrom', cents: 65000 },
  { category: 'unissex', name: 'Mussamam White', cents: 65000 },
  { category: 'unissex', name: 'Ravine Ginger', cents: 65000 },

  // CUIDADOS PESSOAIS
  { category: 'cuidados', name: 'SALVO Body Cream', cents: 23000 },
  { category: 'cuidados', name: 'Body Cream Asad', cents: 30000 },
  { category: 'cuidados', name: 'Retinal Shot', cents: 35000 },
];
